export const ActionTypes = {
  SET_COUNTRIES: "SET_COUNTRIES",
  SET_COUNTRY: "SET_COUNTRY",
  SET_POSTS: "SET_POSTS",
  SET_POST: "SET_POST",
  SET_POST_INPUTS: "SET_POST_INPUTS",
  SET_COMMENTS: "SET_COMMENTS",
  SET_COMMENT_INPUTS: "SET_COMMENT_INPUTS",
};
